### ISSUE TITLE
Add support for data types

### ISSUE THREAD

**Issue by scossu** [aic-collections/aicdams-geneva#4]
- Add an optional `data_type` parameter for each table field definition in the sync config file that specifies a data type for properties
- Specify a default data type for properties with unspecified types (either none or `xsd:string`)
- Data type label should use namespace prefixes registered in Geneva (e.g. "xsd")

**Comment by scossu** [comment]
Looking at the currently imported resources, it seems like there is some sort of automatic mapping based on the data type of the table columns. Is that correct, @acoburn ? 

In that case, this ticket would be to specify an override and would have a much lower priority.

**Comment by acoburn** [comment]
The data type for each field can be set in the JSON-LD file.
